DAWEB/Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.DatHang = new HashSet<DatHang>();
        }
    
        public int Id { get; set; }
        public string images { get; set; }
        public string Name { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<int> IdSP { get; set; }
        public string Mota { get; set; }
        public Nullable<int> TB { get; set; }
    
        public virtual DanhMucSanPham DanhMucSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatHang> DatHang { get; set; }
    }
}

DAWEB/Areas/Admin/Controllers/SanPhamController.cs
using DAWEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Net;
using System.Data;




namespace DAWEB.Areas.Admin.Controllers
{
    public class SanPhamController : Controller
    {
        WebDataEntities3 db = new WebDataEntities3();
        // GET: Admin/SanPham
        public ActionResult Index()
        {
            List<SanPham> lst = db.SanPham.ToList();
            ViewBag.IdSP = new SelectList(db.DanhMucSanPham, "Id", "Name");
            return View(lst);
        }

        public ActionResult Create()
        {
            ViewBag.IdSP = new SelectList(db.DanhMucSanPham, "Id", "Name");

            return View();
        }

        // POST: Admin/Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,images,Name,Gia,Giamgia,IdSP,TB,Mota")] SanPham SP)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    string fileName = "";
                    var f = Request.Files["fileImg"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string[] ext = f.FileName.Split('.');
                        fileName = DateTime.Now.ToString("yyyyMMddHHmmssffff") + "." + ext[ext.Length - 1];
                        string path = Server.MapPath("~/Images/" + fileName);
                        f.SaveAs(path);
                    }
                    ViewBag.fileName = fileName;
                    SP.images = fileName;
                    db.SanPham.Add(SP);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Message = ex.ToString();
                }
            }
            ViewBag.categoryID = new SelectList(db.SanPham, "Id", "name", SP.Id);
            return View(SP);
        }


        public ActionResult Delete(int ID)
        {
            // lấy dữ liệu của Category theo Id tương ứng
            SanPham obj = db.SanPham.Find(ID);
            return View(obj);
        }
        public ActionResult DeleteByID(int ID)
        {
            SanPham obj = db.SanPham.Find(ID);
            db.SanPham.Remove(obj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult Edit(int? ID)
        {
            if (ID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham SP = db.SanPham.Find(ID);

            if (SP == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdSP = new SelectList(db.DanhMucSanPham, "Id", "Name", SP.IdSP);
            return View(SP);
        }

        // POST: Admin/Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,images,Name,Gia,Giamgia,IdSP,TB,Mota")] SanPham SP)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    string fileName = "";
                    var f = Request.Files["fileImg"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string[] ext = f.FileName.Split('.');
                        fileName = DateTime.Now.ToString("yyyyMMddHHmmssffff") + "." + ext[ext.Length - 1];
                        string path = Server.MapPath("~/images/" + fileName);
                        f.SaveAs(path);
                    }
                    SP.images = fileName;
                    db.Entry(SP).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Message = ex.ToString();
                }
                return RedirectToAction("Index");
            }
            ViewBag.categoryID = new SelectList(db.SanPham, "id", "name", SP.Id);
            return View(SP);
        }



        //public ActionResult Edit(int ID)
        //{
        //    // lấy dữ liệu của Category theo Id tương ứng
        //    SanPham SP = db.SanPham.Find(ID);
        //    return View(SP);
        //}
        //public ActionResult EditbyID(SanPham SP)
        //{
        //    // lấy dữ liệu của Category theo Id tương ứng
        //    var f = Request.Files["fileImg"];
        //    if (f != null && f.ContentLength > 0)
        //    {
        //        string[] ext = f.FileName.Split('.');
        //        string fileName = DateTime.Now.ToString("yyyyMMddHHmmssffff") + '.' + ext[ext.Length - 1];
        //        string path = Server.MapPath("~/images/" + fileName);
        //        f.SaveAs(path);
        //        SP.images = "/images/" + fileName;
        //        db.Entry(SP).State = EntityState.Modified;
        //    }
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}
        // GET: Product
        public ActionResult Search(int? IdSP, string Search)
        {
            List<SanPham> LSP;
            if (IdSP == null && Search == null)
            {
                LSP = db.SanPham.ToList();
            }
            else
            {
                if (IdSP != null)
                {
                    LSP = db.SanPham.Where(x => x.Id == IdSP).ToList();
                }
                else
                {
                    LSP = db.SanPham.Where(x => x.Name.Contains(Search)).ToList();
                }
            }

            ViewBag.category = new SelectList(db.DanhMucSanPham.ToList(), "Id", "Name");

            return View(LSP);
        }
        public ActionResult show(int ID)
        {
            // lấy dữ liệu của Category theo Id tương ứng
            SanPham SP = db.SanPham.Find(ID);
            return View(SP);
        }
        public ActionResult showbyID(SanPham SP)
        {
            SanPham obj = db.SanPham.Find(SP);
            List<SanPham> lst = db.SanPham.ToList();
            return View(lst);
        }
    }
}

DAWEB/Areas/Admin/Views/SanPham/Create.cshtml
@model DAWEB.Models.SanPham

@{
    Layout = null;
    Layout = "~/Areas/Admin/Views/Shared/ViewPage1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
    <style>
        div {
            margin-bottom: 10px;
        }
        .IP {
            background-color: #6ebfc2;
            color: #fff;
        }
    </style>
</head>
<body>
    <div style="position: absolute; width: 1130px; right: 10px">

        @using (Html.BeginForm("Create", "SanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Sản phẩm</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="control-label col-md-2">Tên</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Loại</label>
                <div class="col-md-10">
                    @Html.DropDownList("IdSP", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdSP, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Giá</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Mô tả Sản Phẩm</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Ảnh</label>
                <div class="col-md-10">
                    <input type="file" name="fileImg" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Thêm" class="btn btn-default IP" />
                </div>
            </div>
        </div>
        }

        <div style="width: 100px; height: 30px; background-color: black; border-radius: 6px; border: 1px solid #000; display: flex; justify-content: center; align-items: center">
            @Html.ActionLink("Quay lại", "Index", null, new { @style = "color: white; font-weight: 600" })
        </div>

    </div>
</body>
</html>

DAWEB/Areas/Admin/Views/SanPham/Delete.cshtml
@model DAWEB.Models.SanPham

@{
    Layout = null;
    Layout = "~/Areas/Admin/Views/Shared/ViewPage1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
    <style>
        div {
            margin-bottom: 10px;
        }
        .IP{

            background-color: #c63d3d;
            color:#fff;
        }
    </style>
</head>
<body>
    <div>
        <div style="position: absolute; width: 1130px; right: 10px">

            @using (Html.BeginForm("DeleteByID", "SanPham", new { ID = Model.Id }))
            {
                <div class="form-horizontal">
                    <h4>Sản phẩm</h4>
                    <hr />
                    <div class="form-group">
                        <div class="col-md-10">
                            @{ string img_path = "/images/" + Model.images; }
                            <img src="@img_path" style="width: 100px" />


                        </div>
                    </div>
                    <div class="form-group" style="display:flex" :>
                        <label class="control-label col-md-2">Tên Sản Phẩm:</label>
                        <div class="col-md-10">
                            @Html.DisplayFor(m => m.Name)
                        </div>
                    </div>
                    <div class="form-group" style="display:flex" :>
                        <label class="control-label col-md-2">Mô tả sản phẩm:</label>
                        <div class="col-md-10">
                            @Html.DisplayFor(m => m.Mota)
                        </div>
                    </div>
                    <div class="form-group" style="display:flex" :>
                        <label class="control-label col-md-2">Giá Sản Phẩm:</label>
                        <div class="col-md-10">

                            @Html.DisplayFor(m => m.Gia)đ
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Xóa" class="btn btn-default IP" />
                        </div>
                    </div>
                </div>
            }

            <div style="width: 100px; height: 30px; background-color: black; border-radius: 6px; border: 1px solid #000; display: flex; justify-content: center; align-items: center">
                @Html.ActionLink("Quay lại", "Index", null, new { @style = "color: white; font-weight: 600" })
            </div>

        </div>

            @*<h2>Thông tin sản phẩm</h2>
            @using (Html.BeginForm("DeleteByID", "SanPham", new { ID = Model.Id }))
            {
                <div>
                    @Html.LabelFor(m => m.Id) :
                    @Html.DisplayFor(m => m.Id)
                </div>
                <div>
                    @Html.LabelFor(m => m.Name) :
                    @Html.DisplayFor(m => m.Name)
                </div>
                <div>
                    <input type="submit" value="Xoa" />
                </div>
            }
        </div>*@
    </div>
</body>
</html>

DAWEB/Areas/Admin/Views/SanPham/Edit.cshtml
@model DAWEB.Models.SanPham

@{
    Layout = null;
    Layout = "~/Areas/Admin/Views/Shared/ViewPage1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>edit</title>
    <style>
        div {
            margin-bottom: 10px;
        }
        .IP {
            background-color: #6ebfc2;
            color: #fff;
        }
    </style>
</head>
<body>

    <div style="position: absolute; width: 1130px; right: 10px">

        @using (Html.BeginForm("Edit", "SanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Sản phẩm</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                <label class="control-label col-md-2">Tên</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Loại</label>
                <div class="col-md-10">
                    @Html.DropDownList("IdSP", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdSP, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Giá</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Mô tả sản phẩm</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Ảnh</label>
                <div class="col-md-10">
                    @{ string img_path = "/images/" + Model.images; }
                    <img src="@img_path" style="width: 100px" />
                    <input type="file" name="fileImg" />

                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-default IP" />
                </div>
            </div>
        </div>
        }

        <div style="width: 100px; height: 30px; background-color: black; border-radius: 6px; border: 1px solid #000; display: flex; justify-content: center; align-items: center">
            @Html.ActionLink("Quay lại", "Index", null, new { @style = "color: white; font-weight: 600" })
        </div>

    </div>

        @*<div>
            <div style="position: absolute; width: 1130px; right: 10px">
                <h2>Sửa thông tin Danh Mục</h2>
                @using (Html.BeginForm("Edit", "SanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div>
                        @Html.LabelFor(m => m.Name) :
                        @Html.TextBoxFor(m => m.Name)
                    </div>
                    <div>
                        <label>Choose file:</label>
                        <input type="file" name="fileImg" />
                        @Html.ViewBag.images
                    </div>
                    <div>
                        @Html.LabelFor(m => m.Gia) :
                        @Html.TextBoxFor(m => m.Gia)
                    </div>
                    <div>
                        @Html.LabelFor(m => m.giamgia) :
                        @Html.TextBoxFor(m => m.giamgia)
                    </div>
                    <div>
                        <input type="submit" value="sửa" />
                    </div>
                }
            </div>
            </div>*@
</body>
</html>

DAWEB/Areas/Admin/Views/SanPham/Index.cshtml
@model List<DAWEB.Models.SanPham>

@{
    Layout = null;
    Layout = "~/Areas/Admin/Views/Shared/ViewPage1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

    <style>
        a {
            color: #fff
        }
            a:hover {
                color: #000;
            }
    </style>
</head>
<body>
    <div style="">
        <div style="position: absolute; width: 1130px; right: 10px">

            <h2>Danh Mục Các Sản Phẩm</h2>
            <div>
                <div style="width: 130px; height: 40px; background-color: #6ebfc2; align-items: center; display: flex; justify-content: center;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif ">
                    @Html.ActionLink("Thêm Mới", "Create")
                </div>
                @using (Html.BeginForm("Search", "SanPham", FormMethod.Get))
                {
                    @*<label>Lọc theo danh mục: </label>
                        <div>
                            @Html.DropDownList("category", "-- Tất cả --")
                        </div>*@
                    <label>Lọc theo tên: </label>
                    <div style="width:200px; height:40px;display:flex;justify-content:space-between;align-items:center">
                        @Html.TextBox("Search")
                        @*@Html.Label("Theo danh muc: ") @Html.DropDownList("DanhMucSanPham", "Tất cả sản phẩm")*@
                        <input type="submit" value="Lọc" />
                    </div>
                }

            <table class="table">
                <thead class="thead-dark" style="background-color: #000000d9;color: aliceblue;">
                <th style="text-align:center">#</th>
                <th style="text-align:center">Tên Sản Phẩm</th>
                <th style="text-align:center">Loại mặt hàng</th>
                <th style="text-align:center">Danh mục hình ảnh</th>
                <th style="text-align:center">Mô tả sản phẩm</th>
                <th style="text-align:center">Giá</th>
                <th style="text-align:center">Sửa</th>
                <th style="text-align:center">Xem sản phẩm </th>
                <th style="text-align:center">Xóa </th>

                </thead>
                @foreach (var item in Model)
                {
                    <tr>
                        <td style="text-align:center">@item.Id</td>
                        <td style="text-align:center">@item.Name</td>
                        <td style="text-align:center">@item.DanhMucSanPham.Name</td>
                        <td style="text-align:center">
                            @{ string img_path = "/images/" + @item.images; }
                            <img src="@img_path" width="100" height="100" />

                        </td>
                        <td style="text-align: center; word-wrap: break-word; ">@item.Mota</td>

                        <td style="text-align:center">@string.Format("{0:#,0}", item.Gia)₫</td>
                        <td style="text-align:center">
                            <div style="width: 90px; height: 40px; background-color: #6ebfc2; align-items: center; display: flex; justify-content: center; margin: auto;border-radius:10px">
                                @Html.ActionLink("Sửa", "Edit", new { ID = item.Id })
                            </div>
                        </td>
                        <td style="text-align:center">
                            <div style="width: 100px; height: 40px; background-color: #aad442; align-items: center; display: flex; justify-content: center; margin: auto; border-radius: 10px ">
                                @Html.ActionLink("Xem", "show", new { ID = item.Id })
                            </div>
                        </td>
                        <td>
                            <div style="width: 80px; height: 40px; background-color: #c63d3d; align-items: center; display: flex; justify-content: center; margin: auto; border-radius: 10px">
                                @Html.ActionLink("Xóa", "Delete", new { ID = item.Id })
                            </div>
                        </td>
                    </tr>
                }
            </table>
            </div>
        </div>
    </div>
</body>
</html>

DAWEB/Areas/Admin/Views/SanPham/Search.cshtml
@model List<DAWEB.Models.SanPham>

@{
    Layout = null;
    Layout = "~/Areas/Admin/Views/Shared/ViewPage1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Search</title>
    <style>
        a {
            color: #fff
        }
        a:hover{
            color:#000;
        }
    </style>
</head>
<body>
    <div>
        <div style="position: absolute; width: 1130px; right: 10px">
            <h2>Danh sách sản phẩm</h2>
            <div>
                <div style="width: 130px; height: 40px; background-color: #6ebfc2; align-items: center; display: flex; justify-content: center;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif ">
                    <a style="font-family:'Agency FB';color:#fff;font-size:30px">
                        @Html.ActionLink("Thêm Mới", "Create")
                    </a>
                </div>

                @using (Html.BeginForm("Search", "SanPham", FormMethod.Get))
                {
                    @*<label>Lọc theo danh mục: </label>
                <div>
                    @Html.DropDownList("category", "-- Tất cả --")
                </div>*@
                    <label>Lọc theo tên: </label>
                    <div style="width:200px; height:40px;display:flex;justify-content:space-between;align-items:center">
                        @Html.TextBox("Search")

                        <input type="submit" value="Lọc" />
                    </div>
                }
            </div>

            <table class="table">
                <thead class="thead-dark" style="background-color: #000000d9;color: aliceblue;">
                <th style="text-align:center">#</th>
                <th style="text-align:center">Tên Sản Phẩm</th>
                <th style="text-align:center">Danh mục hình ảnh</th>
                <th style="text-align:center">Mô tả sản phẩm</th>
                <th style="text-align:center">Giá</th>
                <th style="text-align:center">Sửa</th>
                <th style="text-align:center">Xem sản phẩm </th>
                <th style="text-align:center">Xóa </th>

                </thead>
                @foreach (var item in Model)
                {
                    <tr>
                        <td style="text-align:center">@item.Id</td>
                        <td style="text-align:center">@item.Name</td>
                        <td style="text-align:center">
                            @{ string img_path = "/images/" + @item.images; }
                            <img src="@img_path" width="100" height="100" />

                        </td>
                        <td style="text-align: center; word-wrap: break-word; ">@item.Mota</td>
                        <td style="text-align:center">@string.Format("{0:#,0}", item.Gia)₫</td>
                        <td style="text-align:center">
                            <div style="width: 90px; height: 40px; background-color: #6ebfc2; align-items: center; display: flex; justify-content: center; margin: auto; border-radius: 10px">
                                @Html.ActionLink("Sửa", "Edit", new { ID = item.Id })
                            </div>
                        </td>
                        <td style="text-align:center">
                            <div style="width: 100px; height: 40px; background-color: #aad442; align-items: center; display: flex; justify-content: center; margin: auto; border-radius: 10px">
                                @Html.ActionLink("Xem", "show", new { ID = item.Id })
                            </div>
                        </td>
                        <td>
                            <div style="width: 80px; height: 40px; background-color: #c63d3d; align-items: center; display: flex; justify-content: center; margin: auto; border-radius: 10px">
                                @Html.ActionLink("Xóa", "Delete", new { ID = item.Id })
                            </div>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</body>
</html>

DAWEB/Areas/Admin/Views/SanPham/show.cshtml
@model DAWEB.Models.SanPham

@{
    Layout = null;
    Layout = "~/Areas/Admin/Views/Shared/ViewPage1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div style="position: absolute; width: 1130px; right: 10px">

        <div style="display:flex;justify-content:space-between;margin-top:50px;margin-bottom:50px">
            <div style="display:flex;justify-content:center;height:100%;width:30%">
                <img alt="@Model.images" src="~/images/@Model.images" width="350" height="350" />
            </div>
            <div style="width:65%">
                <div style="display: flex; margin: 0; font-size: 35px; width: 1400px; align-items: center; margin-bottom: 20px;">
                    <label class="control-label col-md-2" style="padding-right: 0px; padding-left: 0px; margin-bottom: 0px;">Tên sản phẩm:</label>
                    <div class="col-md-10" style="font-size:30px">
                        @Html.DisplayFor(m => m.Name)
                    </div>
                </div>
                <div style="display: flex; margin: 0; font-size: 22px; width: 1000px; align-items: center; margin-bottom: 20px;">
                    <label class="control-label col-md-2" style="padding-right: 0px; padding-left: 0px; margin-bottom: 0px;">Loại sản phẩm:</label>
                    <div class="col-md-10" style="font-size:18px">
                        @Html.DisplayFor(m => m.DanhMucSanPham.Name)
                    </div>
                </div>
                <div style="display: flex; margin: 0; font-size: 22px; width: 1100px; align-items: center; margin-bottom: 20px;">
                    <label class="control-label col-md-2" style="padding-right: 0px; padding-left: 0px; margin-bottom: 0px;">Mô tả Sản Phẩm:</label>
                    <div class="col-md-10" style="font-size:18px">
                        @Html.DisplayFor(m => m.Mota)
                    </div>
                </div>
                <div style="display: flex; margin: 0; font-size: 22px; width: 1000px; align-items: center; margin-bottom: 20px; ">
                    <label class="control-label col-md-2" style="padding-right: 0px; padding-left: 0px; margin-bottom: 0px;">Giá Sản Phẩm:</label>
                    <div class="col-md-10" style="font-size:18px">
                        @string.Format("{0:#,0}", @Model.Gia)₫
                    </div>
                </div>

            </div>
        </div>
        <div style="width: 100px; height: 30px; background-color: black; border-radius: 6px; border: 1px solid #000; display: flex; justify-content: center; align-items: center">
            @Html.ActionLink("Quay lại", "Index", null, new { @style = "color: white; font-weight: 600" })
        </div>
    </div>
</body>
</html>