DAWEB/Areas/Admin/Controllers/ThongKeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Net;
using System.Data;
using DAWEB.Models;

namespace DAWEB.Areas.Admin.Controllers
{
    public class ThongKeController : Controller
    {
        WebDataEntities3 db = new WebDataEntities3();

        // GET: Admin/ThongKe
        public ActionResult Index()
        {
            List<DatHang> lst = db.DatHang.ToList();
            ViewBag.MaKH = new SelectList(db.KhachHang, "MaKH", "TenKH");
            ViewBag.IdTrangThai = new SelectList(db.TrangThai, "IdTrangThai", "Name");
            //ViewBag.MaPhieuDat = new SelectList(db.Dathang, "MaPhieuDat", "MaCTPhieuDat");
            ViewBag.Id = new SelectList(db.SanPham, "Id", "Name");
            return View(lst);
        }
        public ActionResult Edit(int? ID)
        {
            if (ID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatHang SP = db.DatHang.Find(ID);

            if (SP == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdTrangThai = new SelectList(db.TrangThai, "Id", "Name", SP.IdTrangThai);
            return View(SP);
        }

        // POST: Admin/Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,IdSanPham,ThoiGianDat,DiaChi,MaKH,SoLuong,ThanhTien,IdTrangThai")] DatHang SP)
        {

            if (ModelState.IsValid)
            {
                try
                {

                    //string fileName = "";
                    //var f = Request.Files["fileImg"];
                    //if (f != null && f.ContentLength > 0)
                    //{
                    //    string[] ext = f.FileName.Split('.');
                    //    fileName = DateTime.Now.ToString("yyyyMMddHHmmssffff") + "." + ext[ext.Length - 1];
                    //    string path = Server.MapPath("~/images/" + fileName);
                    //    f.SaveAs(path);
                    //}
                    //SP.images = fileName;
                    db.Entry(SP).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Message = ex.ToString();
                }
                return RedirectToAction("Index");
            }
            ViewBag.DatHang = new SelectList(db.DatHang, "Id", "IdTrangThai", SP.Id);
            return View(SP);
        }
    }
}

DAWEB/Areas/Admin/Views/ThongKe/Edit.cshtml
@model DAWEB.Models.DatHang

@{
    Layout = null;
    Layout = "~/Areas/Admin/Views/Shared/ViewPage1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>edit</title>
    <style>
        div {
            margin-bottom: 10px;
        }

        .IP {
            background-color: #6ebfc2;
            color: #fff;
        }
    </style>
</head>
<body>

    <div style="position: absolute; width: 1130px; right: 10px">

        @using (Html.BeginForm("Edit", "ThongKe", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>xác nhận</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            <div class="form-group">
                <label class="control-label col-md-2">Trạng Thái </label>
                <div class="col-md-10">
                    @Html.DropDownList("IdTrangThai", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdTrangThai, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="display:none">
                <label class="control-label col-md-2">ID Sản phẩm</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IdSanPham, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IdSanPham, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group" style="display:none">
                <label class="control-label col-md-2">ID Sản phẩm</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ThoiGianDat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ThoiGianDat, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group" style="display:none">
                <label class="control-label col-md-2">ID Sản phẩm</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MaKH, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaKH, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group" @*style="display:none"*@>
                <label class="control-label col-md-2">Địa chỉ </label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group" style="display:none">
                <label class="control-label col-md-2">Số lượng</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group" style="display:none">
                <label class="control-label col-md-2">Tổng tiền</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ThanhTien, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ThanhTien, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-default IP" />
                </div>
            </div>
        </div>
        }

        <div style="width: 100px; height: 30px; background-color: black; border-radius: 6px; border: 1px solid #000; display: flex; justify-content: center; align-items: center">
            @Html.ActionLink("Quay lại", "Index", null, new { @style = "color: white; font-weight: 600" })
        </div>

    </div>
</body>
</html>

DAWEB/Areas/Admin/Views/ThongKe/Index.cshtml
@model List<DAWEB.Models.DatHang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/ViewPage1.cshtml";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

    <style>
        a {
            color: #fff
        }

            a:hover {
                color: #000;
            }
    </style>
</head>
<body>
    <div style="">
        <div style="position: absolute; width: 1130px; right: 10px">

            <h2>Quản lý đơn hàng</h2>
            <div>


                <table class="table">
                    <thead class="thead-dark" style="background-color: #000000d9;color: aliceblue;">
                    <th style="text-align:center">#</th>
                    <th style="text-align:center">Tên khách hàng</th>
                    <th style="text-align:center">SDT</th>
                    <th style="text-align:center">Tên Sản phẩm</th>
                    <th style="text-align:center">Số lượng</th>
                    <th style="text-align:center">Giá</th>
                    <th style="text-align:center">Thời gian đặt</th>
                    <th style="text-align:center">Địa chỉ</th>
                    <th style="text-align:center">Thành tiền</th>
                    <th style="text-align:center">Trang Thái</th>
                    <th style="text-align:center">Cập nhật đơn hàng </th>
                    @*<th style="text-align:center">Xem sản phẩm </th>*@

                    </thead>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style="text-align:center">@item.Id</td>
                            <td style="text-align:center">@item.KhachHang.TenKH</td>
                            <td style="text-align:center">@item.KhachHang.SDT</td>
                            <td style="text-align:center">@item.SanPham.Name</td>
                            <td style="text-align:center">@item.SoLuong</td>
                            <td style="text-align:center">@item.SanPham.Gia</td>
                            <td style="text-align:center">@string.Format("{0:dd/MM/yyy}", item.ThoiGianDat)</td>
                            <td style="text-align:center">@item.DiaChi</td>
                            <td style="text-align:center">@item.ThanhTien</td>
                            <td style="text-align:center">@item.TrangThai.Name</td>
                            <td>
                                <div style="width: 90px; height: 40px; background-color: #6ebfc2; align-items: center; display: flex; justify-content: center; margin: auto;border-radius:10px">
                                    @Html.ActionLink("Update ", "Edit", new { ID = item.Id })
                                </div>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</body>
</html>