DAWEB/Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.DatHang = new HashSet<DatHang>();
        }
    
        public int Id { get; set; }
        public string images { get; set; }
        public string Name { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<int> IdSP { get; set; }
        public string Mota { get; set; }
        public Nullable<int> TB { get; set; }
    
        public virtual DanhMucSanPham DanhMucSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatHang> DatHang { get; set; }
    }
}

DAWEB/Areas/Admin/Controllers/SanPhamController.cs
using DAWEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Net;
using System.Data;




namespace DAWEB.Areas.Admin.Controllers
{
    public class SanPhamController : Controller
    {
        WebDataEntities3 db = new WebDataEntities3();
        // GET: Admin/SanPham
        public ActionResult Index()
        {
            List<SanPham> lst = db.SanPham.ToList();
            ViewBag.IdSP = new SelectList(db.DanhMucSanPham, "Id", "Name");
            return View(lst);
        }

        public ActionResult Create()
        {
            ViewBag.IdSP = new SelectList(db.DanhMucSanPham, "Id", "Name");

            return View();
        }

        // POST: Admin/Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,images,Name,Gia,Giamgia,IdSP,TB,Mota")] SanPham SP)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    string fileName = "";
                    var f = Request.Files["fileImg"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string[] ext = f.FileName.Split('.');
                        fileName = DateTime.Now.ToString("yyyyMMddHHmmssffff") + "." + ext[ext.Length - 1];
                        string path = Server.MapPath("~/Images/" + fileName);
                        f.SaveAs(path);
                    }
                    ViewBag.fileName = fileName;
                    SP.images = fileName;
                    db.SanPham.Add(SP);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Message = ex.ToString();
                }
            }
            ViewBag.categoryID = new SelectList(db.SanPham, "Id", "name", SP.Id);
            return View(SP);
        }


        public ActionResult Delete(int ID)
        {
            // lấy dữ liệu của Category theo Id tương ứng
            SanPham obj = db.SanPham.Find(ID);
            return View(obj);
        }
        public ActionResult DeleteByID(int ID)
        {
            SanPham obj = db.SanPham.Find(ID);
            db.SanPham.Remove(obj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult Edit(int? ID)
        {
            if (ID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham SP = db.SanPham.Find(ID);

            if (SP == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdSP = new SelectList(db.DanhMucSanPham, "Id", "Name", SP.IdSP);
            return View(SP);
        }

        // POST: Admin/Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,images,Name,Gia,Giamgia,IdSP,TB,Mota")] SanPham SP)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    string fileName = "";
                    var f = Request.Files["fileImg"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string[] ext = f.FileName.Split('.');
                        fileName = DateTime.Now.ToString("yyyyMMddHHmmssffff") + "." + ext[ext.Length - 1];
                        string path = Server.MapPath("~/images/" + fileName);
                        f.SaveAs(path);
                    }
                    SP.images = fileName;
                    db.Entry(SP).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Message = ex.ToString();
                }
                return RedirectToAction("Index");
            }
            ViewBag.categoryID = new SelectList(db.SanPham, "id", "name", SP.Id);
            return View(SP);
        }



        //public ActionResult Edit(int ID)
        //{
        //    // lấy dữ liệu của Category theo Id tương ứng
        //    SanPham SP = db.SanPham.Find(ID);
        //    return View(SP);
        //}
        //public ActionResult EditbyID(SanPham SP)
        //{
        //    // lấy dữ liệu của Category theo Id tương ứng
        //    var f = Request.Files["fileImg"];
        //    if (f != null && f.ContentLength > 0)
        //    {
        //        string[] ext = f.FileName.Split('.');
        //        string fileName = DateTime.Now.ToString("yyyyMMddHHmmssffff") + '.' + ext[ext.Length - 1];
        //        string path = Server.MapPath("~/images/" + fileName);
        //        f.SaveAs(path);
        //        SP.images = "/images/" + fileName;
        //        db.Entry(SP).State = EntityState.Modified;
        //    }
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}
        // GET: Product
        public ActionResult Search(int? IdSP, string Search)
        {
            List<SanPham> LSP;
            if (IdSP == null && Search == null)
            {
                LSP = db.SanPham.ToList();
            }
            else
            {
                if (IdSP != null)
                {
                    LSP = db.SanPham.Where(x => x.Id == IdSP).ToList();
                }
                else
                {
                    LSP = db.SanPham.Where(x => x.Name.Contains(Search)).ToList();
                }
            }

            ViewBag.category = new SelectList(db.DanhMucSanPham.ToList(), "Id", "Name");

            return View(LSP);
        }
        public ActionResult show(int ID)
        {
            // lấy dữ liệu của Category theo Id tương ứng
            SanPham SP = db.SanPham.Find(ID);
            return View(SP);
        }
        public ActionResult showbyID(SanPham SP)
        {
            SanPham obj = db.SanPham.Find(SP);
            List<SanPham> lst = db.SanPham.ToList();
            return View(lst);
        }
    }
}

DAWEB/Controllers/TrangChuController.cs
using DAWEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Data.Entity;

namespace DAWEB.Controllers
{
    public class TrangChuController : Controller
    {
        WebDataEntities3 db = new WebDataEntities3();
        // GET: TrangChu
        public ActionResult Index()
        {
            // tạo dbContext
            // lấy ra danh sách các sản phẩm truy vấn dữ liệu từ Category
            List<SanPham> lst = db.SanPham.ToList();
            var check1 = (from item in db.SanPham orderby item.Gia ascending select item).ToList();
            var check2 = (from item in db.SanPham orderby item.Gia descending select item).ToList();
            return View(lst);
        }
        public ActionResult SanPham(int? Category, string Search)
        {
            List<SanPham> lst;
            if (Category == null && Search == null)
            {
                lst = db.SanPham.ToList();
            }
            else
            {
                if (Category != null)
                {
                    lst = db.SanPham.Where(x => x.IdSP == Category).ToList();
                }
                else
                {
                    lst = db.SanPham.Where(x => x.Name.Contains(Search)).ToList();
                }
            }

            ViewBag.IdSP = new SelectList(db.DanhMucSanPham.ToList(), "Id", "Name");
            return View(lst);
        }
        public ActionResult Detail(int id)
        {
            var objproduct = db.SanPham.Where(n => n.Id == id).FirstOrDefault();
            return View(objproduct);
        }
        public ActionResult GioiThieu()
        {
            return View();
        }
    }
}

DAWEB/Views/TrangChu/Detail.cshtml
@model  DAWEB.Models.SanPham
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/TrangChu.cshtml";
}
<div style="width:100%;background-color:#fff">

<div class="body_main">
    <div class="Box_main">
        <div class="Box_main_left">
            <div class="left_top">
                <img class="SP_img" src="~/images/@Model.images" alt="">

            </div>
        </div>
        <div class="Box_main_right">
            <div class="right_title">
                <a class="top-contentleft_text" href="Trangchu.html">TRANG CHỦ</a>
                <p> &nbsp; / &nbsp;&nbsp; </p>
                <a class="top-contentleft_text" href="Sanpham.html" style="color: black;"><b>CỬA HÀNG</b></a>
            </div>
            <div>
                <h1 style="color:crimson">
                    @Model.Name
                </h1>
            </div>
            <div>
                <h2>
                    @string.Format("{0:#,0}", Model.Gia)₫
                </h2>
            </div>
            <div>
                <h2 style="margin-bottom:0px ;">
                    Mô tả:  @Model.Mota
                </h2>
            </div>
            <div style="display: flex;justify-content: space-between;align-items: center; width: 120px;height: 50px;">
                <h4>Chất liệu: </h4>
                <p>  </p>
            </div>
            <div style="display: flex;justify-content: space-between;align-items: center; width: 230px;height: 50px;">
                <h4>Hạn bảo hành: </h4>
                <p>  </p>
            </div>
            <div style="display: flex;justify-content: space-between;align-items: center; width: 230px;height: 50px;">
                <h4>Loại bảo hành:</h4>
                <p>  </p>
            </div>
            <div style="display: flex;justify-content: space-between;align-items: center; width: 120px;height: 50px;">
                <h4>Kho hàng:</h4>
                <p> </p>
            </div>
            <div style="display: flex;justify-content: space-between;align-items: center; width: 120px;height: 50px;">
                <h4>Gửi từ:</h4>
                <p> </p>
            </div>
            <div style="display: flex;justify-content: space-between;align-items:center; width: 300px;height: 50px;">
                @*<div>
                        <input type="number" id="tentacles" name="tentacles" min="1" max="100" value="1">
                    </div>*@
                <div>
                    <a 
                       href="/Cart/AddToCart/@Model.Id"
                       class="detail">Thêm vào giỏ</a>
                </div>
            </div>
        </div>
    </div>

    <div class="mid">
        <div class="mid-main">
            <div class="mid-top">
                <div class="top-item">
                    <a class="top-item-text" style="color: black;" href="">MÔ TẢ</a>
                </div>
                <div class="top-item1">
                    <a class="top-item-text text" href="">ĐÁNH GIÁ (0)</a>
                </div>
            </div>
            <div class="mid-bottom">
                <div style="height: 200px;width: 1190px;margin: auto;padding-top: 40px;">
                    <p class="text1" style="margin-bottom: 20px;">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam fringilla augue nec est tristique auctor.
                        Donec non est at libero vulputate rutrum. Morbi ornare lectus quis justo gravida semper.
                        Nulla tellus mi, vulputate adipiscing cursus eu, suscipit id nulla.
                    </p>
                    <p class="text1">
                        Pellentesque aliquet, sem eget laoreet ultrices, ipsum metus feugiat sem, quis fermentum turpis eros egetvelit.
                        Donec ac tempus ante. Fusce ultricies massa massa. Fusce aliquam, purus eget sagittis vulputate, sapien libero hendrerit est, sed commodo augue nisi non neque.
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, lorem et placerat vestibulum, metus nisi posuere nisl, in accumsan elit odio quis mi. Cras neque metus, consequat et blandit et, luctus a nunc.
                        Etiam gravida vehicula tellus, in imperdiet ligula euismod eget.
                    </p>
                </div>
            </div>
        </div>
    </div>


</div>
</div>

DAWEB/Views/TrangChu/Index.cshtml
@model List<DAWEB.Models.SanPham>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/TrangChu.cshtml";
}
<!-- body -->
<!-- <div style="height: 1000px;"></div> -->
<div class="bodySilder">
    <div class="slider">
        <div class="slides">
            <input type="radio" name="radio-btn" id="radio1">
            <input type="radio" name="radio-btn" id="radio2">
            <input type="radio" name="radio-btn" id="radio3">


            <div class="slide first">
                <img src="~/images/slider1.jpg" alt="">
            </div>
            <div class="slide ">
                <img src="~/images/slider2.jpg" alt="">
            </div>
            <div class="slide ">
                <img src="~/images/slider3.jpg" alt="">
            </div>

            <div class="navigation-auto">
                <div class="auto-btn1">

                </div>
                <div class="auto-btn2">

                </div>
                <div class="auto-btn3">

                </div>
            </div>
        </div>
        <div class="navigation-manual">
            <label for="radio1" class="manual-btn"></label>
            <label for="radio2" class="manual-btn"></label>
            <label for="radio3" class="manual-btn"></label>
        </div>
    </div>

</div>
<div class="box_slider">
    <h1 style="font-family: 'times new roman', times, serif;color: #f1f1f1;">KHUYẾN MÃI CUỐI NĂM</h1>
    <P style="color: #f1f1f1;">
        Lorem ipsum dolor sit amet, consectetuer
        adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet
        dolore magna aliquam erat volutpat.
    </P>

    <div style="margin-top: 40px;width: 100%;">
        <a>XEM NGAY</a>
    </div>
</div>
<div class="cskh">
    <div class="itemcskh">
        <img src="~/images/1.PNG" alt="">
        <h3 class="textcskh">Miễn phí giao hàng</h3>
        <p class=" size">Giao hàng</p>
        <p class=" size">
            tận nơi khắp các tỉnh thành trên cả nước
        </p>
    </div>
    <div class="itemcskh">
        <img src="~/images/2.PNG" alt="">
        <h3 class="textcskh">Đổi trả sản phẩm</h3>
        <p class=" size">Hoàn lại 100% tiền nếu không vừa ý hoặc lỗi từ nhà</p>
        <p class=" size">
            sản xuất (trong 7 ngày)
        </p>
    </div>
    <div class="itemcskh">
        <img src="~/images/3.PNG" alt="">
        <h3 lass="textcskh">Ưu đãi thành viên</h3>
        <p class=" size">Giảm 20% cho</p>
        <p class=" size">
            thành viên hoặc khách hàng có thẻ thành viên
        </p>
    </div>
    <div class="itemcskh">
        <img src="~/images/4.PNG" alt="">
        <h3 class="textcskh">Hỗ trợ khách hàng</h3>
        <p class=" size">Đội ngũ tư vấn viên, chăm sóc khách hàng luôn sẵn</p>
        <p class=" size">
            sàng hỗ trợ 24/7
        </p>
    </div>
</div>


<!-- tabs -->
<div style="background-color: #212121;padding-top: 30px;">
    <!-- Tab items -->
    <div class="tabs">
        <div class="tab-item active">
            SẢN PHẨM MỚI
        </div>
        <div class="tab-item">
            SẢN PHẨM BÁN CHẠY
        </div>
        <div class="tab-item">
            KHUYẾN MÃI
        </div>
        <div class="line"></div>
    </div>

    <!-- Tab content -->
    <div class="tab-content">
        <div class="tab-pane active">
            <div class="frames">
                @foreach (var item in Model)
                {
                    if (item.TB == 1)
                    {
                        <div class="frames_box">
                            <div class="box_img">
                                <a href="@Url.Action("Detail", "TrangChu", new {id = item.Id})">
                                    <img src="~/images/@item.images" alt="logo" class="frames_box_img">
                                </a>
                            </div>
                            <div class="frames_text">
                                <p>@item.Name </p>
                            </div>
                            <div class="frames_text_price">
                                <p>@string.Format("{0:#,0}", item.Gia)₫</p>
                            </div>
                            <div style="margin-top: 30px; text-align: center;">
                                <a  href="/Cart/AddToCart/@item.Id" class="frames_button_buy">THÊM VÀO GIỎ</a>
                            </div>
                        </div>
                    }
                }
            </div>
            <div class="frames">
                @foreach (var item in Model)
                {
                    if (item.TB == 2)
                    {
                        <div class="frames_box">
                            <div class="box_img">
                                <a href="@Url.Action("Detail", "TrangChu", new {id = item.Id})">
                                    <img src="~/images/@item.images" alt="logo" class="frames_box_img">
                                </a>
                            </div>
                            <div class="frames_text">
                                <p>@item.Name </p>
                            </div>
                            <div class="frames_text_price">
                                <p>@string.Format("{0:#,0}", item.Gia)₫</p>
                            </div>
                            <div style="margin-top: 30px; text-align: center;">
                                <a  href="/Cart/AddToCart/@item.Id" class="frames_button_buy">THÊM VÀO GIỎ</a>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
        <div class="tab-pane">
            <div class="frames">
                @foreach (var item in Model)
                {
                    if (item.TB == 2)
                    {
                        <div class="frames_box">
                            <div class="box_img">
                                <a href="@Url.Action("Detail", "TrangChu", new {id = item.Id})">
                                    <img src="~/images/@item.images" alt="logo" class="frames_box_img">
                                </a>
                            </div>
                            <div class="frames_text">
                                <p>@item.Name </p>
                            </div>
                            <div class="frames_text_price">
                                <p>@string.Format("{0:#,0}", item.Gia)₫</p>
                            </div>
                            <div style="margin-top: 30px; text-align: center;">
                                <a  href="/Cart/AddToCart/@item.Id" class="frames_button_buy">THÊM VÀO GIỎ</a>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
        <div class="tab-pane">
            <div class="frames">
                @foreach (var item in Model)
                {
                    if (item.TB == 1)
                    {
                        <div class="frames_box">
                            <div class="box_img">
                                <a href="@Url.Action("Detail", "TrangChu", new {id = item.Id})">
                                    <img src="~/images/@item.images" alt="logo" class="frames_box_img">
                                </a>
                            </div>
                            <div class="frames_text">
                                <p>@item.Name </p>
                            </div>
                            <div class="frames_text_price">
                                <p>@string.Format("{0:#,0}", item.Gia)₫</p>
                            </div>
                            <div style="margin-top: 30px; text-align: center;">
                                <a  href="/Cart/AddToCart/@item.Id" class="frames_button_buy">THÊM VÀO GIỎ</a>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>
<!-- end tabs -->

<div class="section_overlay">
    <div>
        <p style="margin: 0 0 0 0;"><span data-text-color="primary">Giảm giá 20% các sản phẩm</span></p>
        <h2 style="margin: 0 0 0 0;">
            <span style="color: #fff; font-family: 'times new roman', times, serif; font-size: 2em; line-height: 120%">
                Xu
                hướng phong
                cách mới 2018
            </span>
        </h2>
        <p><span style="color: #999999;">Lorem ipsum dolor sit amet, consectetur adipiscing elit</span></p>
        <div style="margin-top: 40px;width: 100%;">
            <a>XEM NGAY</a>
        </div>
    </div>
</div>

<div class="bodySilder" style="margin-top: 0px;">
    <div style="display: flex;justify-content: center;align-items: center;">
        <h1 style="color: #fff  ;">SẢN PHẨM XEM NHIỀU NHẤT</h1>
    </div>
    <div class="sliderSP">
        <div class="slidesSP" id="slider">
            <input type="radio" name="radioSP-btn" id="radioSP1">
            <input type="radio" name="radioSP-btn" id="radioSP2">
            <input type="radio" name="radioSP-btn" id="radioSP3">

            <div class="slideSP first1">

                @foreach (var item in Model)
                {
                    if (item.TB == 2)
                    {
                        <div class="frames_box">
                            <div class="box_img">
                                <a href="@Url.Action("Detail", "TrangChu", new {id = item.Id})">
                                    <img src="~/images/@item.images" alt="logo" class="frames_box_img">
                                </a>
                            </div>
                            <div class="frames_text">
                                <p>@item.Name </p>
                            </div>
                            <div class="frames_text_price">
                                <p>@string.Format("{0:#,0}", item.Gia)₫</p>
                            </div>
                            <div style="margin-top: 30px; text-align: center;">
                                <a  href="/Cart/AddToCart/@item.Id" class="frames_button_buy">THÊM VÀO GIỎ</a>
                            </div>
                        </div>
                    }
                }

            </div>
            <div class="slideSP " style="justify-content: space-between;">
                    @foreach(var item in Model)
            {
                        if(item.TB == 1)
                {
                <div class="frames_box">
                    <div class="box_img">
                        <a href="@Url.Action("Detail", "TrangChu", new {id = item.Id})">
                            <img src="~/images/@item.images" alt="logo" class="frames_box_img">
                        </a>
                    </div>
                    <div class="frames_text">
                        <p>@item.Name </p>
                    </div>
                    <div class="frames_text_price">
                        <p>@string.Format("{0:#,0}", item.Gia)₫</p>
                    </div>
                    <div style="margin-top: 30px; text-align: center;">
                        <a  href="/Cart/AddToCart/@item.Id" class="frames_button_buy">THÊM VÀO GIỎ</a>
                    </div>
                </div>
                }
            }
            </div>
        </div>
        <div class="navigationSP-auto">
            <div class="autoSP-btn1"></div>
            <div class="autoSP-btn1"></div>
            <div class="autoSP-btn1"></div>

        </div>
        <div class="navigationSP-manual">
            <label for="radioSP1" class="manualSP-btn"></label>
            <label for="radioSP2" class="manualSP-btn"></label>
            <label for="radioSP3" class="manualSP-btn"></label>
        </div>
    </div>
    <div style="margin-top: 00px;">
        <div>
            <i onclick="slider_left()" class="slide_btn_left icon icon_color fa-solid fa-chevron-left"></i>
        </div>
        <div>
            <i onclick="slider_right()" class="slide_btn_right icon icon_color fa-solid fa-chevron-right"></i>
        </div>
    </div>
</div>

<div class="section_content">
    <div class="box_image">
        <img src="/images/img1-bottom-mirora1.jpg">
        <div class="position_img">
            <div>
                <p style="margin: 0 0 0 0;color: #fff;">Sản phẩm mới</p>
                <h2 style="margin: 0 0 0 0;">
                    <span style="color: #a8741a; font-family: 'times new roman', times, serif; font-size: 150%; line-height: 120%">
                        Luxury Perfume 2023
                    </span>
                </h2>
                <p><span style="color: #fff;">Phụ kiện dành cho nam & nữ</span></p>
            </div>
        </div>
    </div>

    <div class="box_image">
        <img src="/images/img2-bottom-mirora1.jpg">
        <div class="position_img">
            <div>
                <p style="margin: 0 0 0 0;color: #fff;">Sản phẩm mới</p>
                <h2 style="margin: 0 0 0 0;">
                    <span style="color: #a8741a; font-family: 'times new roman', times, serif; font-size: 150%; line-height: 120%">
                        Luxury Perfume 2023
                    </span>
                </h2>
                <p><span style="color: #fff;">Phụ kiện dành cho nam & nữ</span></p>
            </div>
        </div>
    </div>
</div>

DAWEB/Views/TrangChu/SanPham.cshtml
@model List<DAWEB.Models.SanPham>

@{
    ViewBag.Title = "SanPham1";
    Layout = "~/Views/Shared/TrangChu.cshtml";
}
<div style="height: 98px;width: 100%;background-color: #353535;">

</div>
<div class="body">
    <div class="body_main">
        <div class="body_top">
            <div class="top-contentleft" style="width:80%">
                <a class="top-contentleft_text" href="/Trangchu/index">TRANG CHỦ</a>
                <p> &nbsp; / &nbsp;&nbsp; </p>
                <a class="top-contentleft_text" href="/Trangchu/SanPham1" style="color: black;"><b>CỬA HÀNG</b></a>
            </div>
            <div class="top-contentright">
                <div>
                    @using (Html.BeginForm("SanPham", "TrangChu", FormMethod.Get))
                    {
                        @*<label>Lọc theo danh mục: </label>
                        <div>
                            @Html.DropDownList("IdSP", "-- Tất cả --")
                        </div>*@
                        <div style="display:flex;justify-content:space-between;align-items:center">
                        <label>Tìm kiếm sản phẩm: </label>
                            @Html.TextBox("Search")
                            <input type="submit" value="Tìm kiếm" />
                        </div>

                    }
                </div>
            </div>
        </div>
    </div>
    <div class="body_main_bt">
        <div class="right_item">
            <div class="item_SP">
                @foreach (var item in Model)
                {
                    <div class="frames_box">
                        <div class="box_img">
                            <a href="@Url.Action("Detail", "TrangChu", new {id = item.Id})">
                                <img src="~/images/@item.images" alt="logo" class="frames_box_img">
                            </a>
                        </div>
                        <div class="frames_text" style="color:black">
                            <p>@item.Name </p>
                        </div>
                        <div class="frames_text_price">
                            <p>@string.Format("{0:#,0}", item.Gia)₫</p>
                        </div>
                        <div style="margin-top: 30px; text-align: center;">
                            <a href="/Cart/AddToCart/@item.Id" class="frames_button_buy">THÊM VÀO GIỎ</a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

</div>